---
abstract: 'Lab::Instrument offers an abstract interface to an instrument that is connected via GPIB, serial connection, ethernet, USB, or whatever else the NI-VISA library supports. In addition Oxford Instruments IsoBus is also supported.'
author:
  - 'Daniel Schroeer <schroeer@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Instrument
provides:
  Lab::Instrument:
    file: lib/Lab/Instrument.pm
    version: 1.0612
  Lab::Instrument::Agilent81134A:
    file: lib/Lab/Instrument/Agilent81134A.pm
    version: 0.0613
  Lab::Instrument::Dummysource:
    file: lib/Lab/Instrument/Dummysource.pm
    version: 0.0613
  Lab::Instrument::HP34401A:
    file: lib/Lab/Instrument/HP34401A.pm
    version: 0.0613
  Lab::Instrument::HP34411A:
    file: lib/Lab/Instrument/HP34411A.pm
    version: 0.0613
  Lab::Instrument::HP34420A:
    file: lib/Lab/Instrument/HP34420A.pm
    version: 0.0613
  Lab::Instrument::HP3458A:
    file: lib/Lab/Instrument/HP3458A.pm
    version: 0.0613
  Lab::Instrument::HP34970A:
    file: lib/Lab/Instrument/HP34970A.pm
    version: 0.0613
  Lab::Instrument::HP8360:
    file: lib/Lab/Instrument/HP8360.pm
    version: 0.0613
  Lab::Instrument::ILM:
    file: lib/Lab/Instrument/ILM.pm
    version: 0.0613
  Lab::Instrument::IOtech488:
    file: lib/Lab/Instrument/IOtech488.pm
    version: 0.0613
  Lab::Instrument::IPS12010new:
    file: lib/Lab/Instrument/IPS12010new.pm
    version: 0.0613
  Lab::Instrument::ITC503:
    file: lib/Lab/Instrument/ITC503.pm
    version: 0.0613
  Lab::Instrument::IsoBus:
    file: lib/Lab/Instrument/IsoBus.pm
    version: 0.0613
  Lab::Instrument::KnickS252:
    file: lib/Lab/Instrument/KnickS252.pm
    version: 0.0613
  Lab::Instrument::Lakeshore336:
    file: lib/Lab/Instrument/Lakeshore336.pm
    version: 0.0613
  Lab::Instrument::Lakeshore370:
    file: lib/Lab/Instrument/Lakeshore370.pm
    version: 0.0613
  Lab::Instrument::MagnetSupply:
    file: lib/Lab/Instrument/MagnetSupply.pm
    version: 1.0613
  Lab::Instrument::SR620:
    file: lib/Lab/Instrument/SR620.pm
  Lab::Instrument::SR780:
    file: lib/Lab/Instrument/SR780.pm
    version: 0.0613
  Lab::Instrument::SR830:
    file: lib/Lab/Instrument/SR830.pm
    version: 0.0613
  Lab::Instrument::SRS_SIM928:
    file: lib/Lab/Instrument/SRS_SIM928.pm
    version: 0.0613
  Lab::Instrument::Source:
    file: lib/Lab/Instrument/Source.pm
    version: 1.0613
  Lab::Instrument::TMRC2:
    file: lib/Lab/Instrument/TMRC2.pm
    version: 0.0613
  Lab::Instrument::TRMC2:
    file: lib/Lab/Instrument/TRMC2.pm
    version: 0.0613
  Lab::Instrument::Yokogawa7651:
    file: lib/Lab/Instrument/Yokogawa7651.pm
    version: 0.0613
requires:
  Lab::VISA: 2.03
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2.00
