--- #YAML:1.0
name: Lab-Instrument
version: 0.01_085
author:
  - Daniel Schroeer <daniel@daimla1.de>
abstract: Worker class for VISA based instrument classes
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
